server:
  port: 9999

maven:
  pass: root
  user: root
  context-path: /maven
  repos:
  - id: release
    name: release
    type: hosted
  - id: snapshots
    name: snapshots
    type: hosted
  - id: aliyun
    name: aliyun
    type: proxy
    proxy-url: http://192.168.99.135:8081/repository/maven-public/
#    proxy-url: http://maven.aliyun.com/nexus/content/groups/public/
  - id: public
    name: public
    type: group
    group:
    - aliyun
    - release
    - snapshots
